services:
  django:
    build:
      context: ..
      dockerfile: .devcontainer/Docker/Dockerfile
    container_name: django
    ports:
      - "8000:8000"
    volumes:
      - ../:/django
    env_file:
      - ../.env
